"""empty message

Revision ID: 085de5b8fb04
Revises: 0b01874d1d94
Create Date: 2021-04-26 13:38:02.722036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085de5b8fb04'
down_revision = '0b01874d1d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reservations_endDate_key', 'reservations', type_='unique')
    op.drop_constraint('reservations_farmId_key', 'reservations', type_='unique')
    op.drop_constraint('reservations_startDate_key', 'reservations', type_='unique')
    op.drop_constraint('reservations_userId_key', 'reservations', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('reservations_userId_key', 'reservations', ['userId'])
    op.create_unique_constraint('reservations_startDate_key', 'reservations', ['startDate'])
    op.create_unique_constraint('reservations_farmId_key', 'reservations', ['farmId'])
    op.create_unique_constraint('reservations_endDate_key', 'reservations', ['endDate'])
    # ### end Alembic commands ###
